version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    user: root
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins_data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net

  # remote_host:
  #   container_name: remote_host
  #   image: remote_host
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ssh
  #   networks:
  #     - net
networks:
  net: